# Generated by Django 4.0.4 on 2022-05-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profile',
            field=models.CharField(choices=[('LM Engineer', 'lm engineer'), ('Quality Manager', 'quality manager'), ('Assistant Engineer', 'assistant engineer')], max_length=18),
        ),
    ]
